version: '3.1'

services:

  webserver:
    build:
        context: ./
    restart: "always"
    ports:
      - "8000:80"
      - "8433:443"
    links:
      - mysql
    volumes:
      - ${REPO_ROOT-./}www/:/var/www/:rw

      #- C/projects/cicd/jenkins/jenkins_home/workspace/project-drupal/www:/var/www/:rw
      #projects/cicd/jenkins/jenkins_home/workspace/project-drupal/www:c
    #  - C/projects/cicd/jenkins/jenkins_home/workspace/project-drupal@2/www/:/var/www/:rw
#      - ./config/vhosts:/etc/apache2/sites-enabled
    environment:
      APACHE_DOCUMENT_ROOT: /var/www/web
      XDEBUG_CONFIG: "remote_host=host.docker.internal remote_port=9003"
    extra_hosts:
      - "host.docker.internal:host-gateway"

  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootPass
      MYSQL_DATABASE: drupal

