version: '3.1'

services:

  webserver:
    build:
      context: ./
#    image: angela1g/drupal-project:latest
    restart: "always"
    ports:
      - "8000:80"
      - "8433:443"
    links:
      - mysql
    volumes:
      - ${REPO_ROOT-./}www/:/var/www/:rw
    environment:
      APACHE_DOCUMENT_ROOT: /var/www/web
      XDEBUG_CONFIG: "remote_host=host.docker.internal remote_port=9003"
    extra_hosts:
      - "host.docker.internal:host-gateway"

  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootPass
      MYSQL_DATABASE: drupal

